CREATE TABLE info (
    user_id INT PRIMARY KEY IDENTITY(1,1),
    atu_id INT UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    userName VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);